name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.6
  - jupyter=1.0.0
  - seaborn=0.12.2
  - matplotlib=3.7.0
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=13.0.0
  - pip:
      - wandb==0.15.11
      - ydata-profiling==4.5.1