name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - requests=2.31.0
  - scikit-learn=1.3.0
  - pip:
      - wandb==0.15.11
      - mlflow==2.7.1
      - protobuf==3.20.*
      # - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
      - git+https://github.com/sakthi-t/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components

