name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - pyyaml=6.0.1
  - hydra-core=1.3.2
  - pip=23.2.1
  - pip:
      - wandb==0.15.11
      - mlflow==2.7.1
      - protobuf==3.20.*