name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.2.1
  - scikit-learn=1.3.0
  - pip:
      - wandb==0.15.11
      - mlflow==2.7.1
      - protobuf==3.20.*
      # https://github.com/sakthi-t/build-ml-pipeline-for-short-term-rental-prices.git
      - git+https://github.com/sakthi-t/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
